using System;
using davidgyongyosi_ADT_2022231.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.IO;
using static System.Net.WebRequestMethods;

namespace davidgyongyosi_ADT_2022231.Repository
{
    public class GamesDbContext : DbContext
    {
        public DbSet<Game> Games { get; set; }
        public DbSet<Platform> Platforms { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<GamePlatform> GamePlatforms { get; set; }

        public GamesDbContext(DbContextOptions<GamesDbContext> opt) : base(opt)
        {
            this.Database.EnsureCreated();
        }

        public GamesDbContext()
        {
            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder builder)
        {
            if (!builder.IsConfigured)
                builder.UseLazyLoadingProxies().UseInMemoryDatabase("GamesDB");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            //One to many connection: Games - Genres
            modelBuilder.Entity<Game>(game => game
                .HasOne(game => game.Genre)
                .WithMany(genre => genre.Games)
                .HasForeignKey(game => game.GenreId));

            modelBuilder.Entity<Game>()
                .HasData(
                new Game() { Id = 1, GenreId = 45, GameName = "Lost Ark", Price = 0, releaseDate = "2022" },
                new Game() { Id = 2, GenreId = 66, GameName = "PUBG: BATTLEGROUNDS", Price = 0, releaseDate = "2017" },
                new Game() { Id = 3, GenreId = 10, GameName = "Apex Legends", Price = 0, releaseDate = "2020" },
                new Game() { Id = 4, GenreId = 30, GameName = "Call of Duty: Modern Warfare II", Price = 69.99, releaseDate = "2022" },
                new Game() { Id = 5, GenreId = 32, GameName = "Team Fortress 2", Price = 0, releaseDate = "2007" },
                new Game() { Id = 6, GenreId = 48, GameName = "Grand Theft Auto V", Price = 0, releaseDate = "2015" },
                new Game() { Id = 7, GenreId = 40, GameName = "New World", Price = 39.99, releaseDate = "2021" },
                new Game() { Id = 8, GenreId = 66, GameName = "Rust", Price = 39.99, releaseDate = "2018" },
                new Game() { Id = 9, GenreId = 66, GameName = "Unturned", Price = 0, releaseDate = "2017" },
                new Game() { Id = 10, GenreId = 56, GameName = "NARAKA: BLADEPOINT", Price = 19.99, releaseDate = "2021" },
                new Game() { Id = 11, GenreId = 74, GameName = "War Thunder", Price = 0, releaseDate = "2013" },
                new Game() { Id = 12, GenreId = 64, GameName = "Sid Meier's Civilization VI", Price = 5.99, releaseDate = "2016" },
                new Game() { Id = 13, GenreId = 58, GameName = "Football Manager 2023", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 14, GenreId = 49, GameName = "ARK: Survival Evolved", Price = 19.99, releaseDate = "2017" },
                new Game() { Id = 15, GenreId = 49, GameName = "Terraria", Price = 9.99, releaseDate = "2011" },
                new Game() { Id = 16, GenreId = 48, GameName = "Destiny 2", Price = 0, releaseDate = "2019" },
                new Game() { Id = 17, GenreId = 18, GameName = "Warhammer: Vermintide 2", Price = 5.99, releaseDate = "2018" },
                new Game() { Id = 18, GenreId = 50, GameName = "MIR4", Price = 0, releaseDate = "2021" },
                new Game() { Id = 19, GenreId = 19, GameName = "RimWorld", Price = 34.99, releaseDate = "2018" },
                new Game() { Id = 20, GenreId = 33, GameName = "Dead by Daylight", Price = 19.99, releaseDate = "2016" },
                new Game() { Id = 21, GenreId = 41, GameName = "Mount & Blade II: Bannerlord", Price = 49.99, releaseDate = "2022" },
                new Game() { Id = 22, GenreId = 55, GameName = "The Sims 4", Price = 0, releaseDate = "2014" },
                new Game() { Id = 23, GenreId = 66, GameName = "DayZ", Price = 44.99, releaseDate = "2018" },
                new Game() { Id = 24, GenreId = 62, GameName = "EA SPORTS FIFA 23", Price = 69.99, releaseDate = "2022" },
                new Game() { Id = 25, GenreId = 4, GameName = "Warframe", Price = 0, releaseDate = "2013" },
                new Game() { Id = 26, GenreId = 18, GameName = "PAYDAY 2", Price = 9.99, releaseDate = "2013" },
                new Game() { Id = 27, GenreId = 21, GameName = "Cyberpunk 2077", Price = 59.99, releaseDate = "2020" },
                new Game() { Id = 28, GenreId = 18, GameName = "Deep Rock Galactic", Price = 29.99, releaseDate = "2020" },
                new Game() { Id = 29, GenreId = 64, GameName = "Hearts of Iron IV", Price = 39.99, releaseDate = "2016" },
                new Game() { Id = 30, GenreId = 60, GameName = "ELDEN RING", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 31, GenreId = 27, GameName = "Stardew Valley", Price = 14.99, releaseDate = "2016" },
                new Game() { Id = 32, GenreId = 30, GameName = "Tom Clancy's Rainbow Six Siege", Price = 19.99, releaseDate = "2015" },
                new Game() { Id = 33, GenreId = 55, GameName = "Garry's Mod", Price = 9.99, releaseDate = "2006" },
                new Game() { Id = 34, GenreId = 48, GameName = "The Elder Scrolls V: Skyrim Special Edition", Price = 39.99, releaseDate = "2016" },
                new Game() { Id = 35, GenreId = 31, GameName = "Victoria 3", Price = 49.99, releaseDate = "2022" },
                new Game() { Id = 36, GenreId = 45, GameName = "FINAL FANTASY XIV Online", Price = 19.99, releaseDate = "2014" },
                new Game() { Id = 37, GenreId = 25, GameName = "Euro Truck Simulator 2", Price = 19.99, releaseDate = "2012" },
                new Game() { Id = 38, GenreId = 58, GameName = "Farming Simulator 22", Price = 39.99, releaseDate = "2021" },
                new Game() { Id = 39, GenreId = 42, GameName = "VRChat", Price = 0, releaseDate = "2017" },
                new Game() { Id = 40, GenreId = 64, GameName = "Total War: WARHAMMER III", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 41, GenreId = 26, GameName = "Don't Starve Together", Price = 14.99, releaseDate = "2016" },
                new Game() { Id = 42, GenreId = 54, GameName = "UNDECEMBER", Price = 0, releaseDate = "2022" },
                new Game() { Id = 43, GenreId = 16, GameName = "Cities: Skylines", Price = 27.99, releaseDate = "2015" },
                new Game() { Id = 44, GenreId = 30, GameName = "Battlefield 1", Price = 39.99, releaseDate = "2016" },
                new Game() { Id = 45, GenreId = 48, GameName = "Red Dead Redemption 2", Price = 59.99, releaseDate = "2019" },
                new Game() { Id = 46, GenreId = 12, GameName = "Yu-Gi-Oh! Master Duel", Price = 0, releaseDate = "2022" },
                new Game() { Id = 47, GenreId = 59, GameName = "FIFA 22", Price = 59.99, releaseDate = "2021" },
                new Game() { Id = 48, GenreId = 48, GameName = "Fallout 4", Price = 19.99, releaseDate = "2015" },
                new Game() { Id = 49, GenreId = 73, GameName = "Sid Meier's Civilization V", Price = 29.99, releaseDate = "2010" },
                new Game() { Id = 50, GenreId = 45, GameName = "Black Desert", Price = 9.99, releaseDate = "2017" },
                new Game() { Id = 51, GenreId = 37, GameName = "Persona 5 Royal", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 52, GenreId = 75, GameName = "Left 4 Dead 2", Price = 9.99, releaseDate = "2009" },
                new Game() { Id = 53, GenreId = 3, GameName = "Brotato", Price = 4.99, releaseDate = "2022" },
                new Game() { Id = 54, GenreId = 64, GameName = "Age of Empires II: Definitive Edition", Price = 19.99, releaseDate = "2019" },
                new Game() { Id = 55, GenreId = 48, GameName = "The Witcher 3: Wild Hunt", Price = 39.99, releaseDate = "2015" },
                new Game() { Id = 56, GenreId = 31, GameName = "Europa Universalis IV", Price = 39.99, releaseDate = "2013" },
                new Game() { Id = 57, GenreId = 53, GameName = "Slay the Spire", Price = 24.99, releaseDate = "2019" },
                new Game() { Id = 58, GenreId = 48, GameName = "Hunt: Showdown", Price = 39.99, releaseDate = "2019" },
                new Game() { Id = 59, GenreId = 54, GameName = "The Elder Scrolls Online", Price = 19.99, releaseDate = "2014" },
                new Game() { Id = 60, GenreId = 64, GameName = "Crusader Kings III", Price = 49.99, releaseDate = "2020" },
                new Game() { Id = 61, GenreId = 3, GameName = "The Binding of Isaac: Rebirth", Price = 14.99, releaseDate = "2014" },
                new Game() { Id = 62, GenreId = 7, GameName = "Factorio", Price = 30, releaseDate = "2020" },
                new Game() { Id = 63, GenreId = 2, GameName = "MONSTER HUNTER RISE", Price = 19.99, releaseDate = "2022" },
                new Game() { Id = 64, GenreId = 61, GameName = "Stellaris", Price = 39.99, releaseDate = "2016" },
                new Game() { Id = 65, GenreId = 72, GameName = "Bloons TD 6", Price = 13.99, releaseDate = "2018" },
                new Game() { Id = 66, GenreId = 18, GameName = "Monster Hunter: World", Price = 29.99, releaseDate = "2018" },
                new Game() { Id = 67, GenreId = 49, GameName = "The Forest", Price = 19.99, releaseDate = "2018" },
                new Game() { Id = 68, GenreId = 2, GameName = "Arma 3", Price = 29.99, releaseDate = "2013" },
                new Game() { Id = 69, GenreId = 28, GameName = "Brawlhalla", Price = 0, releaseDate = "2017" },
                new Game() { Id = 70, GenreId = 36, GameName = "NBA 2K23", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 71, GenreId = 66, GameName = "Conan Exiles", Price = 39.99, releaseDate = "2018" },
                new Game() { Id = 72, GenreId = 70, GameName = "World of Tanks Blitz", Price = 0, releaseDate = "2016" },
                new Game() { Id = 73, GenreId = 2, GameName = "God of War", Price = 49.99, releaseDate = "2022" },
                new Game() { Id = 74, GenreId = 75, GameName = "Dying Light", Price = 29.99, releaseDate = "2015" },
                new Game() { Id = 75, GenreId = 13, GameName = "Stumble Guys", Price = 0, releaseDate = "2021" },
                new Game() { Id = 76, GenreId = 44, GameName = "Squad", Price = 44.99, releaseDate = "2020" },
                new Game() { Id = 77, GenreId = 46, GameName = "SMITE", Price = 0, releaseDate = "2015" },
                new Game() { Id = 78, GenreId = 3, GameName = "Vampire Survivors", Price = 4.99, releaseDate = "2022" },
                new Game() { Id = 79, GenreId = 58, GameName = "Microsoft Flight Simulator 40th Anniversary Edition", Price = 59.99, releaseDate = "2020" },
                new Game() { Id = 80, GenreId = 71, GameName = "Risk of Rain 2", Price = 24.99, releaseDate = "2020" },
                new Game() { Id = 81, GenreId = 66, GameName = "Grounded", Price = 39.99, releaseDate = "2022" },
                new Game() { Id = 82, GenreId = 22, GameName = "Fallout 76: The Pitt", Price = 39.99, releaseDate = "2020" },
                new Game() { Id = 83, GenreId = 2, GameName = "Counter-Strike", Price = 9.99, releaseDate = "2000" },
                new Game() { Id = 84, GenreId = 24, GameName = "Geometry Dash", Price = 3.99, releaseDate = "2014" },
                new Game() { Id = 85, GenreId = 17, GameName = "Cookie Clicker", Price = 4.99, releaseDate = "2021" },
                new Game() { Id = 86, GenreId = 4, GameName = "Path of Exile", Price = 0, releaseDate = "2013" },
                new Game() { Id = 87, GenreId = 52, GameName = "Forza Horizon 5", Price = 59.99, releaseDate = "2021" },
                new Game() { Id = 88, GenreId = 66, GameName = "Dread Hunger", Price = 29.99, releaseDate = "2022" },
                new Game() { Id = 89, GenreId = 64, GameName = "Age of Empires IV: Anniversary Edition", Price = 39.99, releaseDate = "2021" },
                new Game() { Id = 90, GenreId = 66, GameName = "Raft", Price = 19.99, releaseDate = "2022" },
                new Game() { Id = 91, GenreId = 62, GameName = "NBA 2K22", Price = 59.99, releaseDate = "2021" },
                new Game() { Id = 92, GenreId = 35, GameName = "Melvor Idle", Price = 9.99, releaseDate = "2021" },
                new Game() { Id = 93, GenreId = 18, GameName = "Dying Light 2 Stay Human", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 94, GenreId = 8, GameName = "American Truck Simulator", Price = 4.99, releaseDate = "2016" },
                new Game() { Id = 95, GenreId = 54, GameName = "Tactics Ogre: Reborn", Price = 49.99, releaseDate = "2022" },
                new Game() { Id = 96, GenreId = 52, GameName = "Assetto Corsa", Price = 19.99, releaseDate = "2014" },
                new Game() { Id = 97, GenreId = 5, GameName = "Sea of Thieves", Price = 39.99, releaseDate = "2020" },
                new Game() { Id = 98, GenreId = 48, GameName = "No Man's Sky", Price = 59.99, releaseDate = "2016" },
                new Game() { Id = 99, GenreId = 52, GameName = "Forza Horizon 4", Price = 0, releaseDate = "2021" },
                new Game() { Id = 100, GenreId = 5, GameName = "Sonic Frontiers", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 101, GenreId = 19, GameName = "Oxygen Not Included", Price = 24.99, releaseDate = "2019" },
                new Game() { Id = 102, GenreId = 61, GameName = "Space Engineers", Price = 19.99, releaseDate = "2019" },
                new Game() { Id = 103, GenreId = 47, GameName = "World of Warships", Price = 0, releaseDate = "2017" },
                new Game() { Id = 104, GenreId = 45, GameName = "Albion Online", Price = 0, releaseDate = "2017" },
                new Game() { Id = 105, GenreId = 69, GameName = "Divinity: Original Sin 2 - Definitive Edition", Price = 44.99, releaseDate = "2017" },
                new Game() { Id = 106, GenreId = 30, GameName = "Battlefield V", Price = 49.99, releaseDate = "2018" },
                new Game() { Id = 107, GenreId = 18, GameName = "Among Us", Price = 4.99, releaseDate = "2018" },
                new Game() { Id = 108, GenreId = 29, GameName = "Russian Fishing 4", Price = 0, releaseDate = "2021" },
                new Game() { Id = 109, GenreId = 55, GameName = "People Playground", Price = 9.99, releaseDate = "2019" },
                new Game() { Id = 110, GenreId = 35, GameName = "Idle Champions of the Forgotten Realms", Price = 0, releaseDate = "2020" },
                new Game() { Id = 111, GenreId = 30, GameName = "Halo Infinite", Price = 0, releaseDate = "2021" },
                new Game() { Id = 112, GenreId = 57, GameName = "Hell Let Loose", Price = 39.99, releaseDate = "2021" },
                new Game() { Id = 113, GenreId = 58, GameName = "Shop Titans", Price = 0, releaseDate = "2020" },
                new Game() { Id = 114, GenreId = 52, GameName = "Need for Speed Heat", Price = 69.99, releaseDate = "2019" },
                new Game() { Id = 115, GenreId = 43, GameName = "Hollow Knight", Price = 14.99, releaseDate = "2017" },
                new Game() { Id = 116, GenreId = 64, GameName = "Company of Heroes 2", Price = 19.99, releaseDate = "2013" },
                new Game() { Id = 117, GenreId = 64, GameName = "Total War: WARHAMMER II", Price = 59.99, releaseDate = "2017" },
                new Game() { Id = 118, GenreId = 5, GameName = "Dead Cells", Price = 24.99, releaseDate = "2018" },
                new Game() { Id = 119, GenreId = 32, GameName = "Paladins", Price = 0, releaseDate = "2018" },
                new Game() { Id = 120, GenreId = 58, GameName = "Farming Simulator 19", Price = 19.99, releaseDate = "2018" },
                new Game() { Id = 121, GenreId = 41, GameName = "Mount & Blade: Warband", Price = 19.99, releaseDate = "2010" },
                new Game() { Id = 122, GenreId = 48, GameName = "Assassin's Creed Odyssey", Price = 59.99, releaseDate = "2018" },
                new Game() { Id = 123, GenreId = 64, GameName = "Total War: THREE KINGDOMS", Price = 59.99, releaseDate = "2019" },
                new Game() { Id = 124, GenreId = 64, GameName = "Total War: ROME II - Emperor Edition", Price = 59.99, releaseDate = "2013" },
                new Game() { Id = 125, GenreId = 3, GameName = "Hades", Price = 24.99, releaseDate = "2020" },
                new Game() { Id = 126, GenreId = 68, GameName = "TableTop Simulator", Price = 19.99, releaseDate = "2015" },
                new Game() { Id = 127, GenreId = 45, GameName = "RuneScape", Price = 0, releaseDate = "2020" },
                new Game() { Id = 128, GenreId = 48, GameName = "Kenshi", Price = 29.99, releaseDate = "2018" },
                new Game() { Id = 129, GenreId = 60, GameName = "Sekiro: Shadows Die Twice - GOTY Edition", Price = 59.99, releaseDate = "2019" },
                new Game() { Id = 130, GenreId = 45, GameName = "STAR WARS: The Old Republic", Price = 0, releaseDate = "2011" },
                new Game() { Id = 131, GenreId = 61, GameName = "EVE Online", Price = 0, releaseDate = "2003" },
                new Game() { Id = 132, GenreId = 28, GameName = "TEKKEN 7", Price = 39.99, releaseDate = "2017" },
                new Game() { Id = 133, GenreId = 48, GameName = "Fallout: New Vegas", Price = 9.99, releaseDate = "2010" },
                new Game() { Id = 134, GenreId = 60, GameName = "DARK SOULS III", Price = 59.99, releaseDate = "2016" },
                new Game() { Id = 135, GenreId = 15, GameName = "Pathfinder: Wrath of the Righteous - Enhanced Edition", Price = 49.99, releaseDate = "2021" },
                new Game() { Id = 136, GenreId = 18, GameName = "Human: Fall Flat", Price = 5.99, releaseDate = "2016" },
                new Game() { Id = 137, GenreId = 61, GameName = "Elite Dangerous", Price = 29.99, releaseDate = "2015" },
                new Game() { Id = 138, GenreId = 64, GameName = "Age of Empires II", Price = 19.99, releaseDate = "2013" },
                new Game() { Id = 139, GenreId = 35, GameName = "NGU IDLE", Price = 0, releaseDate = "2019" },
                new Game() { Id = 140, GenreId = 34, GameName = "theHunter: Call of the Wild", Price = 19.99, releaseDate = "2017" },
                new Game() { Id = 141, GenreId = 65, GameName = "Marvel's Spider-Man Remastered", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 142, GenreId = 72, GameName = "Plants vs.  Zombies GOTY Edition", Price = 4.99, releaseDate = "2009" },
                new Game() { Id = 143, GenreId = 64, GameName = "XCOM 2", Price = 59.99, releaseDate = "2016" },
                new Game() { Id = 144, GenreId = 52, GameName = "F1 22", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 145, GenreId = 57, GameName = "Battlefield 2042", Price = 59.99, releaseDate = "2021" },
                new Game() { Id = 146, GenreId = 54, GameName = "Tower of Fantasy", Price = 0, releaseDate = "2022" },
                new Game() { Id = 147, GenreId = 54, GameName = "Borderlands 3", Price = 59.99, releaseDate = "2020" },
                new Game() { Id = 148, GenreId = 39, GameName = "Planet Zoo", Price = 44.99, releaseDate = "2019" },
                new Game() { Id = 149, GenreId = 59, GameName = "eFootball 2023", Price = 0, releaseDate = "2021" },
                new Game() { Id = 150, GenreId = 30, GameName = "Gunfire Reborn", Price = 19.99, releaseDate = "2021" },
                new Game() { Id = 151, GenreId = 12, GameName = "Yu-Gi-Oh! Duel Links", Price = 0, releaseDate = "2017" },
                new Game() { Id = 152, GenreId = 40, GameName = "Foxhole", Price = 29.99, releaseDate = "2022" },
                new Game() { Id = 153, GenreId = 18, GameName = "PlateUp!", Price = 17.99, releaseDate = "2022" },
                new Game() { Id = 154, GenreId = 4, GameName = "Grim Dawn", Price = 24.99, releaseDate = "2016" },
                new Game() { Id = 155, GenreId = 61, GameName = "Kerbal Space Program", Price = 39.99, releaseDate = "2015" },
                new Game() { Id = 156, GenreId = 48, GameName = "Far Cry 5", Price = 59.99, releaseDate = "2018" },
                new Game() { Id = 157, GenreId = 73, GameName = "Darkest Dungeon", Price = 24.99, releaseDate = "2016" },
                new Game() { Id = 158, GenreId = 2, GameName = "Bendy and the Dark Revival", Price = 29.99, releaseDate = "2022" },
                new Game() { Id = 159, GenreId = 35, GameName = "Idle Skilling", Price = 0, releaseDate = "2022" },
                new Game() { Id = 160, GenreId = 48, GameName = "The Elder Scrolls V: Skyrim", Price = 19.99, releaseDate = "2011" },
                new Game() { Id = 161, GenreId = 48, GameName = "Days Gone", Price = 49.99, releaseDate = "2021" },
                new Game() { Id = 162, GenreId = 64, GameName = "Total War: MEDIEVAL II Definitive Edition", Price = 24.99, releaseDate = "2006" },
                new Game() { Id = 163, GenreId = 18, GameName = "It Takes Two", Price = 39.99, releaseDate = "2021" },
                new Game() { Id = 164, GenreId = 45, GameName = "Guild Wars 2", Price = 0, releaseDate = "2022" },
                new Game() { Id = 165, GenreId = 74, GameName = "Crossout Vehicular Combat", Price = 0, releaseDate = "2017" },
                new Game() { Id = 166, GenreId = 57, GameName = "Counter-Strike: Source", Price = 9.99, releaseDate = "2004" },
                new Game() { Id = 167, GenreId = 48, GameName = "ASTRONEER", Price = 29.99, releaseDate = "2016" },
                new Game() { Id = 168, GenreId = 64, GameName = "Age of Empires III: Definitive Edition", Price = 19.99, releaseDate = "2020" },
                new Game() { Id = 169, GenreId = 63, GameName = "Mass Effect Legendary Edition", Price = 59.99, releaseDate = "2021" },
                new Game() { Id = 170, GenreId = 31, GameName = "Crusader Kings II", Price = 0, releaseDate = "2012" },
                new Game() { Id = 171, GenreId = 75, GameName = "Killing Floor 2", Price = 29.99, releaseDate = "2016" },
                new Game() { Id = 172, GenreId = 58, GameName = "SnowRunner", Price = 29.99, releaseDate = "2021" },
                new Game() { Id = 173, GenreId = 64, GameName = "Lords Mobile", Price = 0, releaseDate = "2019" },
                new Game() { Id = 174, GenreId = 54, GameName = "For The King", Price = 19.99, releaseDate = "2018" },
                new Game() { Id = 175, GenreId = 9, GameName = "They Are Billions", Price = 29.99, releaseDate = "2019" },
                new Game() { Id = 176, GenreId = 6, GameName = "BLEACH Brave Souls", Price = 0, releaseDate = "2020" },
                new Game() { Id = 177, GenreId = 41, GameName = "FOR HONOR", Price = 14.99, releaseDate = "2017" },
                new Game() { Id = 178, GenreId = 66, GameName = "The Cycle: Frontier", Price = 0, releaseDate = "2022" },
                new Game() { Id = 179, GenreId = 16, GameName = "Northgard", Price = 0, releaseDate = "2018" },
                new Game() { Id = 180, GenreId = 58, GameName = "Transport Fever 2", Price = 0, releaseDate = "2019" },
                new Game() { Id = 181, GenreId = 55, GameName = "Totally Accurate Battle Simulator", Price = 19.99, releaseDate = "2021" },
                new Game() { Id = 182, GenreId = 35, GameName = "Leaf Blower Revolution - Idle Game", Price = 0, releaseDate = "2020" },
                new Game() { Id = 183, GenreId = 45, GameName = "MapleStory", Price = 0, releaseDate = "2012" },
                new Game() { Id = 184, GenreId = 38, GameName = "Borderlands 2", Price = 19.99, releaseDate = "2012" },
                new Game() { Id = 185, GenreId = 29, GameName = "Fishing Planet", Price = 0, releaseDate = "2015" },
                new Game() { Id = 186, GenreId = 17, GameName = "Clicker Heroes", Price = 0, releaseDate = "2015" },
                new Game() { Id = 187, GenreId = 33, GameName = "SCP: Secret Laboratory", Price = 0, releaseDate = "2017" },
                new Game() { Id = 188, GenreId = 49, GameName = "Subnautica", Price = 29.99, releaseDate = "2018" },
                new Game() { Id = 189, GenreId = 2, GameName = "Devil May Cry 5", Price = 29.99, releaseDate = "2019" },
                new Game() { Id = 190, GenreId = 30, GameName = "Call of Duty: Black Ops III", Price = 14.99, releaseDate = "2015" },
                new Game() { Id = 191, GenreId = 45, GameName = "Phantasy Star Online 2 New Genesis", Price = 0, releaseDate = "2020" },
                new Game() { Id = 192, GenreId = 17, GameName = "AdVenture Capitalist", Price = 0, releaseDate = "2015" },
                new Game() { Id = 193, GenreId = 1, GameName = "ASTLIBRA Revision", Price = 24.99, releaseDate = "2022" },
                new Game() { Id = 194, GenreId = 30, GameName = "Insurgency: Sandstorm", Price = 29.99, releaseDate = "2018" },
                new Game() { Id = 195, GenreId = 14, GameName = "Detroit: Become Human", Price = 39.99, releaseDate = "2020" },
                new Game() { Id = 196, GenreId = 67, GameName = "Resident Evil Village", Price = 39.99, releaseDate = "2021" },
                new Game() { Id = 197, GenreId = 70, GameName = "World of Tanks", Price = 0, releaseDate = "2021" },
                new Game() { Id = 198, GenreId = 2, GameName = "Gotham Knights", Price = 59.99, releaseDate = "2022" },
                new Game() { Id = 199, GenreId = 23, GameName = "Teardown", Price = 19.99, releaseDate = "2022" },
                new Game() { Id = 200, GenreId = 48, GameName = "Middle-earth: Shadow of War", Price = 49.99, releaseDate = "2017" },
                new Game() { Id = 201, GenreId = 51, GameName = "Goose Goose Duck", Price = 0, releaseDate = "2021" },
                new Game() { Id = 202, GenreId = 58, GameName = "House Flipper", Price = 24.99, releaseDate = "2018" },
                new Game() { Id = 203, GenreId = 54, GameName = "Nioh 2 The Complete Edition", Price = 49.99, releaseDate = "2021" },
                new Game() { Id = 204, GenreId = 64, GameName = "Total War: EMPIRE Definitive Edition", Price = 24.99, releaseDate = "2009" },
                new Game() { Id = 205, GenreId = 16, GameName = "Frostpunk", Price = 29.99, releaseDate = "2018" },
                new Game() { Id = 206, GenreId = 48, GameName = "Horizon Zero Dawn Complete Edition", Price = 49.99, releaseDate = "2020" },
                new Game() { Id = 207, GenreId = 17, GameName = "Cell to Singularity - Evolution Never Ends", Price = 0, releaseDate = "2021" },
                new Game() { Id = 208, GenreId = 41, GameName = "Kingdom Come: Deliverance", Price = 29.99, releaseDate = "2018" },
                new Game() { Id = 209, GenreId = 52, GameName = "CarX Drift Racing Online", Price = 14.99, releaseDate = "2017" },
                new Game() { Id = 210, GenreId = 11, GameName = "Shadowverse CCG", Price = 0, releaseDate = "2016" },
                new Game() { Id = 211, GenreId = 20, GameName = "TRAHA Global", Price = 0, releaseDate = "2022" },
                new Game() { Id = 212, GenreId = 66, GameName = "Medieval Dynasty", Price = 34.99, releaseDate = "2021" },
                new Game() { Id = 213, GenreId = 58, GameName = "My Singing Monsters", Price = 0, releaseDate = "2021" },
                new Game() { Id = 214, GenreId = 30, GameName = "Counter-Strike: Global Offensive", Price = 0, releaseDate = "2012" },
                new Game() { Id = 215, GenreId = 46, GameName = "Dota 2", Price = 0, releaseDate = "2013" });

            modelBuilder.Entity<Genre>()
                .HasData(
                new Genre() { GenreName = "2D", Id = 1 },
                new Genre() { GenreName = "Action", Id = 2 },
                new Genre() { GenreName = "Action Roguelike", Id = 3 },
                new Genre() { GenreName = "Action RPG", Id = 4 },
                new Genre() { GenreName = "Adventure", Id = 5 },
                new Genre() { GenreName = "Anime", Id = 6 },
                new Genre() { GenreName = "Automation", Id = 7 },
                new Genre() { GenreName = "Automobile Sim", Id = 8 },
                new Genre() { GenreName = "Base Building", Id = 9 },
                new Genre() { GenreName = "Battle Royal", Id = 10 },
                new Genre() { GenreName = "Card Battler", Id = 11 },
                new Genre() { GenreName = "Card Game", Id = 12 },
                new Genre() { GenreName = "Casual", Id = 13 },
                new Genre() { GenreName = "Choices Matter", Id = 14 },
                new Genre() { GenreName = "Choose Your Own Adventure", Id = 15 },
                new Genre() { GenreName = "City Builder", Id = 16 },
                new Genre() { GenreName = "Clicker", Id = 17 },
                new Genre() { GenreName = "Co-op", Id = 18 },
                new Genre() { GenreName = "Colony Sim", Id = 19 },
                new Genre() { GenreName = "Combat", Id = 20 },
                new Genre() { GenreName = "Cyberpunk", Id = 21 },
                new Genre() { GenreName = "Dark Comedy", Id = 22 },
                new Genre() { GenreName = "Destruction", Id = 23 },
                new Genre() { GenreName = "Difficult", Id = 24 },
                new Genre() { GenreName = "Driving Top", Id = 25 },
                new Genre() { GenreName = "Exploration", Id = 26 },
                new Genre() { GenreName = "Farming Sim", Id = 27 },
                new Genre() { GenreName = "Fighting", Id = 28 },
                new Genre() { GenreName = "Fishing", Id = 29 },
                new Genre() { GenreName = "FPS", Id = 30 },
                new Genre() { GenreName = "Grand Strategy", Id = 31 },
                new Genre() { GenreName = "Hero Shooter", Id = 32 },
                new Genre() { GenreName = "Horror", Id = 33 },
                new Genre() { GenreName = "Hunting", Id = 34 },
                new Genre() { GenreName = "Idler", Id = 35 },
                new Genre() { GenreName = "Immersive Sim", Id = 36 },
                new Genre() { GenreName = "JRPG", Id = 37 },
                new Genre() { GenreName = "Loot", Id = 38 },
                new Genre() { GenreName = "Management", Id = 39 },
                new Genre() { GenreName = "Massively Multiplayer", Id = 40 },
                new Genre() { GenreName = "Medieval", Id = 41 },
                new Genre() { GenreName = "Memes", Id = 42 },
                new Genre() { GenreName = "Metroidvania", Id = 43 },
                new Genre() { GenreName = "Military", Id = 44 },
                new Genre() { GenreName = "MMORPG", Id = 45 },
                new Genre() { GenreName = "MOBA", Id = 46 },
                new Genre() { GenreName = "Naval Combat", Id = 47 },
                new Genre() { GenreName = "Open World", Id = 48 },
                new Genre() { GenreName = "Open World Survival Craft", Id = 49 },
                new Genre() { GenreName = "PvE", Id = 50 },
                new Genre() { GenreName = "PvP", Id = 51 },
                new Genre() { GenreName = "Racing", Id = 52 },
                new Genre() { GenreName = "Roguelike", Id = 53 },
                new Genre() { GenreName = "RPG", Id = 54 },
                new Genre() { GenreName = "Sandbox", Id = 55 },
                new Genre() { GenreName = "Sexual Content", Id = 56 },
                new Genre() { GenreName = "Shooter", Id = 57 },
                new Genre() { GenreName = "Simulation", Id = 58 },
                new Genre() { GenreName = "Soccer", Id = 59 },
                new Genre() { GenreName = "Souls-like", Id = 60 },
                new Genre() { GenreName = "Space", Id = 61 },
                new Genre() { GenreName = "Sports", Id = 62 },
                new Genre() { GenreName = "Story Rich", Id = 63 },
                new Genre() { GenreName = "Strategy", Id = 64 },
                new Genre() { GenreName = "Superhero", Id = 65 },
                new Genre() { GenreName = "Survival", Id = 66 },
                new Genre() { GenreName = "Survival Horror", Id = 67 },
                new Genre() { GenreName = "Table Top", Id = 68 },
                new Genre() { GenreName = "Tactical RPG", Id = 69 },
                new Genre() { GenreName = "Tanks", Id = 70 },
                new Genre() { GenreName = "Third-Person Shooter", Id = 71 },
                new Genre() { GenreName = "Tower Defence", Id = 72 },
                new Genre() { GenreName = "Turn-Based", Id = 73 },
                new Genre() { GenreName = "Vehicular Combat", Id = 74 },
                new Genre() { GenreName = "Zombies", Id = 75 });

            modelBuilder.Entity<Platform>()
                .HasData(
                new Platform() { PlatformName = "Windows", Id = 1 },
                new Platform() { PlatformName = "Linux", Id = 2 },
                new Platform() { PlatformName = "Mac", Id = 3 });

            modelBuilder.Entity<Game>()
                .HasMany(g => g.Platforms)
                .WithMany(p => p.Games)
                .UsingEntity<GamePlatform>(
                    g => g.HasOne<Platform>().WithMany().HasForeignKey(gp => gp.PlatformId),
                    p => p.HasOne<Game>().WithMany().HasForeignKey(gp => gp.GameId),
                    gp =>
                    {
                        gp.HasKey("GameId", "PlatformId");
                        gp.HasData(
                new { GameId = 1, PlatformId = 1 },
                new { GameId = 2, PlatformId = 1 },
                new { GameId = 3, PlatformId = 1 },
                new { GameId = 4, PlatformId = 1 },
                new { GameId = 5, PlatformId = 3 },
                new { GameId = 5, PlatformId = 2 },
                new { GameId = 5, PlatformId = 1 },
                new { GameId = 6, PlatformId = 1 },
                new { GameId = 7, PlatformId = 1 },
                new { GameId = 8, PlatformId = 3 },
                new { GameId = 8, PlatformId = 1 },
                new { GameId = 9, PlatformId = 3 },
                new { GameId = 9, PlatformId = 2 },
                new { GameId = 9, PlatformId = 1 },
                new { GameId = 10, PlatformId = 1 },
                new { GameId = 11, PlatformId = 3 },
                new { GameId = 11, PlatformId = 2 },
                new { GameId = 11, PlatformId = 1 },
                new { GameId = 12, PlatformId = 3 },
                new { GameId = 12, PlatformId = 2 },
                new { GameId = 12, PlatformId = 1 },
                new { GameId = 13, PlatformId = 3 },
                new { GameId = 13, PlatformId = 1 },
                new { GameId = 14, PlatformId = 3 },
                new { GameId = 14, PlatformId = 1 },
                new { GameId = 15, PlatformId = 3 },
                new { GameId = 15, PlatformId = 2 },
                new { GameId = 15, PlatformId = 1 },
                new { GameId = 16, PlatformId = 1 },
                new { GameId = 17, PlatformId = 1 },
                new { GameId = 18, PlatformId = 1 },
                new { GameId = 19, PlatformId = 3 },
                new { GameId = 19, PlatformId = 2 },
                new { GameId = 19, PlatformId = 1 },
                new { GameId = 20, PlatformId = 1 },
                new { GameId = 21, PlatformId = 1 },
                new { GameId = 22, PlatformId = 1 },
                new { GameId = 23, PlatformId = 1 },
                new { GameId = 24, PlatformId = 1 },
                new { GameId = 25, PlatformId = 1 },
                new { GameId = 26, PlatformId = 2 },
                new { GameId = 26, PlatformId = 1 },
                new { GameId = 27, PlatformId = 1 },
                new { GameId = 28, PlatformId = 1 },
                new { GameId = 29, PlatformId = 3 },
                new { GameId = 29, PlatformId = 2 },
                new { GameId = 29, PlatformId = 1 },
                new { GameId = 30, PlatformId = 1 },
                new { GameId = 31, PlatformId = 3 },
                new { GameId = 31, PlatformId = 2 },
                new { GameId = 31, PlatformId = 1 },
                new { GameId = 32, PlatformId = 1 },
                new { GameId = 33, PlatformId = 3 },
                new { GameId = 33, PlatformId = 2 },
                new { GameId = 33, PlatformId = 1 },
                new { GameId = 34, PlatformId = 1 },
                new { GameId = 35, PlatformId = 3 },
                new { GameId = 35, PlatformId = 2 },
                new { GameId = 35, PlatformId = 1 },
                new { GameId = 36, PlatformId = 1 },
                new { GameId = 37, PlatformId = 3 },
                new { GameId = 37, PlatformId = 2 },
                new { GameId = 37, PlatformId = 1 },
                new { GameId = 38, PlatformId = 3 },
                new { GameId = 38, PlatformId = 1 },
                new { GameId = 39, PlatformId = 1 },
                new { GameId = 40, PlatformId = 3 },
                new { GameId = 40, PlatformId = 2 },
                new { GameId = 40, PlatformId = 1 },
                new { GameId = 41, PlatformId = 3 },
                new { GameId = 41, PlatformId = 2 },
                new { GameId = 41, PlatformId = 1 },
                new { GameId = 42, PlatformId = 1 },
                new { GameId = 43, PlatformId = 3 },
                new { GameId = 43, PlatformId = 2 },
                new { GameId = 43, PlatformId = 1 },
                new { GameId = 44, PlatformId = 1 },
                new { GameId = 45, PlatformId = 1 },
                new { GameId = 46, PlatformId = 1 },
                new { GameId = 47, PlatformId = 1 },
                new { GameId = 48, PlatformId = 1 },
                new { GameId = 49, PlatformId = 3 },
                new { GameId = 49, PlatformId = 2 },
                new { GameId = 49, PlatformId = 1 },
                new { GameId = 50, PlatformId = 1 },
                new { GameId = 51, PlatformId = 1 },
                new { GameId = 52, PlatformId = 3 },
                new { GameId = 52, PlatformId = 2 },
                new { GameId = 52, PlatformId = 1 },
                new { GameId = 53, PlatformId = 1 },
                new { GameId = 54, PlatformId = 1 },
                new { GameId = 55, PlatformId = 1 },
                new { GameId = 56, PlatformId = 3 },
                new { GameId = 56, PlatformId = 2 },
                new { GameId = 56, PlatformId = 1 },
                new { GameId = 57, PlatformId = 3 },
                new { GameId = 57, PlatformId = 2 },
                new { GameId = 57, PlatformId = 1 },
                new { GameId = 58, PlatformId = 1 },
                new { GameId = 59, PlatformId = 3 },
                new { GameId = 59, PlatformId = 1 },
                new { GameId = 60, PlatformId = 3 },
                new { GameId = 60, PlatformId = 2 },
                new { GameId = 60, PlatformId = 1 },
                new { GameId = 61, PlatformId = 3 },
                new { GameId = 61, PlatformId = 2 },
                new { GameId = 61, PlatformId = 1 },
                new { GameId = 62, PlatformId = 3 },
                new { GameId = 62, PlatformId = 2 },
                new { GameId = 62, PlatformId = 1 },
                new { GameId = 63, PlatformId = 1 },
                new { GameId = 64, PlatformId = 3 },
                new { GameId = 64, PlatformId = 2 },
                new { GameId = 64, PlatformId = 1 },
                new { GameId = 65, PlatformId = 3 },
                new { GameId = 65, PlatformId = 1 },
                new { GameId = 66, PlatformId = 1 },
                new { GameId = 67, PlatformId = 1 },
                new { GameId = 68, PlatformId = 1 },
                new { GameId = 69, PlatformId = 3 },
                new { GameId = 69, PlatformId = 1 },
                new { GameId = 70, PlatformId = 1 },
                new { GameId = 71, PlatformId = 1 },
                new { GameId = 72, PlatformId = 3 },
                new { GameId = 72, PlatformId = 1 },
                new { GameId = 73, PlatformId = 1 },
                new { GameId = 74, PlatformId = 3 },
                new { GameId = 74, PlatformId = 2 },
                new { GameId = 74, PlatformId = 1 },
                new { GameId = 75, PlatformId = 1 },
                new { GameId = 76, PlatformId = 1 },
                new { GameId = 77, PlatformId = 1 },
                new { GameId = 78, PlatformId = 3 },
                new { GameId = 78, PlatformId = 1 },
                new { GameId = 79, PlatformId = 1 },
                new { GameId = 80, PlatformId = 1 },
                new { GameId = 81, PlatformId = 1 },
                new { GameId = 82, PlatformId = 1 },
                new { GameId = 83, PlatformId = 3 },
                new { GameId = 83, PlatformId = 2 },
                new { GameId = 83, PlatformId = 1 },
                new { GameId = 84, PlatformId = 3 },
                new { GameId = 84, PlatformId = 1 },
                new { GameId = 85, PlatformId = 1 },
                new { GameId = 86, PlatformId = 3 },
                new { GameId = 86, PlatformId = 1 },
                new { GameId = 87, PlatformId = 1 },
                new { GameId = 88, PlatformId = 1 },
                new { GameId = 89, PlatformId = 1 },
                new { GameId = 90, PlatformId = 1 },
                new { GameId = 91, PlatformId = 1 },
                new { GameId = 92, PlatformId = 3 },
                new { GameId = 92, PlatformId = 2 },
                new { GameId = 92, PlatformId = 1 },
                new { GameId = 93, PlatformId = 1 },
                new { GameId = 94, PlatformId = 3 },
                new { GameId = 94, PlatformId = 2 },
                new { GameId = 94, PlatformId = 1 },
                new { GameId = 95, PlatformId = 1 },
                new { GameId = 96, PlatformId = 1 },
                new { GameId = 97, PlatformId = 1 },
                new { GameId = 98, PlatformId = 1 },
                new { GameId = 99, PlatformId = 1 },
                new { GameId = 100, PlatformId = 1 },
                new { GameId = 101, PlatformId = 3 },
                new { GameId = 101, PlatformId = 2 },
                new { GameId = 101, PlatformId = 1 },
                new { GameId = 102, PlatformId = 1 },
                new { GameId = 103, PlatformId = 1 },
                new { GameId = 104, PlatformId = 3 },
                new { GameId = 104, PlatformId = 2 },
                new { GameId = 104, PlatformId = 1 },
                new { GameId = 105, PlatformId = 3 },
                new { GameId = 105, PlatformId = 1 },
                new { GameId = 106, PlatformId = 1 },
                new { GameId = 107, PlatformId = 1 },
                new { GameId = 108, PlatformId = 1 },
                new { GameId = 109, PlatformId = 1 },
                new { GameId = 110, PlatformId = 3 },
                new { GameId = 110, PlatformId = 1 },
                new { GameId = 111, PlatformId = 1 },
                new { GameId = 112, PlatformId = 1 },
                new { GameId = 113, PlatformId = 1 },
                new { GameId = 114, PlatformId = 1 },
                new { GameId = 115, PlatformId = 3 },
                new { GameId = 115, PlatformId = 2 },
                new { GameId = 115, PlatformId = 1 },
                new { GameId = 116, PlatformId = 3 },
                new { GameId = 116, PlatformId = 2 },
                new { GameId = 116, PlatformId = 1 },
                new { GameId = 117, PlatformId = 3 },
                new { GameId = 117, PlatformId = 2 },
                new { GameId = 117, PlatformId = 1 },
                new { GameId = 118, PlatformId = 3 },
                new { GameId = 118, PlatformId = 2 },
                new { GameId = 118, PlatformId = 1 },
                new { GameId = 119, PlatformId = 3 },
                new { GameId = 119, PlatformId = 1 },
                new { GameId = 120, PlatformId = 3 },
                new { GameId = 120, PlatformId = 1 },
                new { GameId = 121, PlatformId = 3 },
                new { GameId = 121, PlatformId = 2 },
                new { GameId = 121, PlatformId = 1 },
                new { GameId = 122, PlatformId = 1 },
                new { GameId = 123, PlatformId = 3 },
                new { GameId = 123, PlatformId = 2 },
                new { GameId = 123, PlatformId = 1 },
                new { GameId = 124, PlatformId = 1 },
                new { GameId = 125, PlatformId = 3 },
                new { GameId = 125, PlatformId = 1 },
                new { GameId = 126, PlatformId = 3 },
                new { GameId = 126, PlatformId = 2 },
                new { GameId = 126, PlatformId = 1 },
                new { GameId = 127, PlatformId = 3 },
                new { GameId = 127, PlatformId = 1 },
                new { GameId = 128, PlatformId = 1 },
                new { GameId = 129, PlatformId = 1 },
                new { GameId = 130, PlatformId = 1 },
                new { GameId = 131, PlatformId = 3 },
                new { GameId = 131, PlatformId = 1 },
                new { GameId = 132, PlatformId = 1 },
                new { GameId = 133, PlatformId = 1 },
                new { GameId = 134, PlatformId = 3 },
                new { GameId = 134, PlatformId = 1 },
                new { GameId = 135, PlatformId = 3 },
                new { GameId = 135, PlatformId = 1 },
                new { GameId = 136, PlatformId = 1 },
                new { GameId = 137, PlatformId = 1 },
                new { GameId = 138, PlatformId = 1 },
                new { GameId = 139, PlatformId = 1 },
                new { GameId = 140, PlatformId = 1 },
                new { GameId = 141, PlatformId = 3 },
                new { GameId = 141, PlatformId = 1 },
                new { GameId = 142, PlatformId = 3 },
                new { GameId = 142, PlatformId = 2 },
                new { GameId = 142, PlatformId = 1 },
                new { GameId = 143, PlatformId = 1 },
                new { GameId = 144, PlatformId = 1 },
                new { GameId = 145, PlatformId = 1 },
                new { GameId = 146, PlatformId = 1 },
                new { GameId = 147, PlatformId = 1 },
                new { GameId = 148, PlatformId = 1 },
                new { GameId = 149, PlatformId = 1 },
                new { GameId = 150, PlatformId = 1 },
                new { GameId = 151, PlatformId = 1 },
                new { GameId = 152, PlatformId = 1 },
                new { GameId = 153, PlatformId = 1 },
                new { GameId = 154, PlatformId = 3 },
                new { GameId = 154, PlatformId = 2 },
                new { GameId = 154, PlatformId = 1 },
                new { GameId = 155, PlatformId = 1 },
                new { GameId = 156, PlatformId = 3 },
                new { GameId = 156, PlatformId = 2 },
                new { GameId = 156, PlatformId = 1 },
                new { GameId = 157, PlatformId = 1 },
                new { GameId = 158, PlatformId = 1 },
                new { GameId = 159, PlatformId = 1 },
                new { GameId = 160, PlatformId = 1 },
                new { GameId = 161, PlatformId = 3 },
                new { GameId = 161, PlatformId = 2 },
                new { GameId = 161, PlatformId = 1 },
                new { GameId = 162, PlatformId = 1 },
                new { GameId = 163, PlatformId = 1 },
                new { GameId = 164, PlatformId = 1 },
                new { GameId = 165, PlatformId = 3 },
                new { GameId = 165, PlatformId = 2 },
                new { GameId = 165, PlatformId = 1 },
                new { GameId = 166, PlatformId = 1 },
                new { GameId = 167, PlatformId = 1 },
                new { GameId = 168, PlatformId = 1 },
                new { GameId = 169, PlatformId = 3 },
                new { GameId = 169, PlatformId = 2 },
                new { GameId = 169, PlatformId = 1 },
                new { GameId = 170, PlatformId = 1 },
                new { GameId = 171, PlatformId = 1 },
                new { GameId = 172, PlatformId = 1 },
                new { GameId = 173, PlatformId = 3 },
                new { GameId = 173, PlatformId = 2 },
                new { GameId = 173, PlatformId = 1 },
                new { GameId = 174, PlatformId = 1 },
                new { GameId = 175, PlatformId = 1 },
                new { GameId = 176, PlatformId = 1 },
                new { GameId = 177, PlatformId = 1 },
                new { GameId = 178, PlatformId = 3 },
                new { GameId = 178, PlatformId = 2 },
                new { GameId = 178, PlatformId = 1 },
                new { GameId = 179, PlatformId = 3 },
                new { GameId = 179, PlatformId = 2 },
                new { GameId = 179, PlatformId = 1 },
                new { GameId = 180, PlatformId = 3 },
                new { GameId = 180, PlatformId = 1 },
                new { GameId = 181, PlatformId = 1 },
                new { GameId = 182, PlatformId = 1 },
                new { GameId = 183, PlatformId = 3 },
                new { GameId = 183, PlatformId = 2 },
                new { GameId = 183, PlatformId = 1 },
                new { GameId = 184, PlatformId = 3 },
                new { GameId = 184, PlatformId = 2 },
                new { GameId = 184, PlatformId = 1 },
                new { GameId = 185, PlatformId = 3 },
                new { GameId = 185, PlatformId = 1 },
                new { GameId = 186, PlatformId = 1 },
                new { GameId = 187, PlatformId = 3 },
                new { GameId = 187, PlatformId = 1 },
                new { GameId = 188, PlatformId = 1 },
                new { GameId = 189, PlatformId = 3 },
                new { GameId = 189, PlatformId = 1 },
                new { GameId = 190, PlatformId = 1 },
                new { GameId = 191, PlatformId = 3 },
                new { GameId = 191, PlatformId = 2 },
                new { GameId = 191, PlatformId = 1 },
                new { GameId = 192, PlatformId = 1 },
                new { GameId = 193, PlatformId = 1 },
                new { GameId = 194, PlatformId = 1 },
                new { GameId = 195, PlatformId = 1 },
                new { GameId = 196, PlatformId = 1 },
                new { GameId = 197, PlatformId = 1 },
                new { GameId = 198, PlatformId = 1 },
                new { GameId = 199, PlatformId = 1 },
                new { GameId = 200, PlatformId = 3 },
                new { GameId = 200, PlatformId = 1 },
                new { GameId = 201, PlatformId = 3 },
                new { GameId = 201, PlatformId = 1 },
                new { GameId = 202, PlatformId = 1 },
                new { GameId = 203, PlatformId = 3 },
                new { GameId = 203, PlatformId = 2 },
                new { GameId = 203, PlatformId = 1 },
                new { GameId = 204, PlatformId = 3 },
                new { GameId = 204, PlatformId = 1 },
                new { GameId = 205, PlatformId = 1 },
                new { GameId = 206, PlatformId = 3 },
                new { GameId = 206, PlatformId = 1 },
                new { GameId = 207, PlatformId = 1 },
                new { GameId = 208, PlatformId = 1 },
                new { GameId = 209, PlatformId = 3 },
                new { GameId = 209, PlatformId = 1 },
                new { GameId = 210, PlatformId = 1 },
                new { GameId = 211, PlatformId = 1 },
                new { GameId = 212, PlatformId = 1 },
                new { GameId = 213, PlatformId = 3 },
                new { GameId = 213, PlatformId = 2 },
                new { GameId = 213, PlatformId = 1 },
                new { GameId = 214, PlatformId = 3 },
                new { GameId = 214, PlatformId = 2 },
                new { GameId = 214, PlatformId = 1 },
                new { GameId = 215, PlatformId = 3 },
                new { GameId = 215, PlatformId = 2 },
                new { GameId = 215, PlatformId = 1 }
                );});

        }
    }
}

